jwt:
  header: Authorization
  expTime: 864000000
  secret_key: my-very-secret-keymy-very-secret-keymy-very-secret-keymy-very-secret-keymy-very-secret-key

gateway:
  ip: 3.37.155.50

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, refresh, health
